spring:
    elasticsearch:
        # Spring Elasticsearch Evolution [MIGRATION]
        password: changeme
        username: changeme
        uris: http://localhost:9200
        evolution:
            historyIndex: icd10-es-evolution
    ai:
        ollama:
            embedding:
                model: nomic-embed-text