PUT /icd10
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "review_vector": {
        "type": "dense_vector",
        "dims": 768,
        "index": true,
        "similarity": "cosine"
      },
      "review_text": {
        "type": "text"
      }
    }
  }
}